FROM node:13-alpine

RUN mkdir -p /usr/app

WORKDIR /usr/app

COPY . .

#COPY ["./package.json", "./yarn.lock"] /usr/app

# RUN rm /usr/local/bin/yarnpkg
# RUN rm /usr/local/bin/yarn
# RUN npm install -g yarn

RUN yarn global add pm2

RUN yarn install

CMD ["pm2-runtime","ecosystem.config.js"]