FROM node:13-alpine

RUN mkdir -p /usr/app

WORKDIR /usr/app

COPY . /usr/app

# COPY ["package.json", "yarn.lock"] /usr/app

RUN yarn install

# RUN npm install --development --silent

RUN adduser -D -u 501 appuser -G jimmy

RUN chown -R duypham:jimmy /app

USER appuser

RUN yarn add global pm2
# CMD ["yarn", "dev"]
CMD ["pm2-runtime", "ecosystem.config.js", "--env", "development"]