FROM mysql:5.7.22

COPY initdb.sql /docker-entrypoint-initdb.d/

RUN ln -sf /usr/share/zoneinfo/Asia/Hanoi /etc/localtime

CMD ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--skip-character-set-client-handshake"]